boot.o: boot.S multiboot.h x86_desc.h types.h
idt_linkage.o: idt_linkage.S
load_paging.o: load_paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_handler.o: idt_handler.c idt_handler.h x86_desc.h types.h lib.h \
  sys_call_handler.h term_keyboard.h keyboard.h RTC.h new_file.h
init_idt.o: init_idt.c init_idt.h x86_desc.h types.h idt_handler.h \
  idt_linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h init_idt.h paging.h keyboard.h RTC.h term_keyboard.h new_file.h \
  sys_call_handler.h
keyboard.o: keyboard.c term_keyboard.h keyboard.h types.h lib.h i8259.h \
  sys_call_handler.h RTC.h new_file.h
lib.o: lib.c lib.h types.h term_keyboard.h keyboard.h
new_file.o: new_file.c new_file.h types.h lib.h sys_call_handler.h \
  term_keyboard.h keyboard.h RTC.h
paging.o: paging.c paging.h types.h load_paging.h
pit_handler.o: pit_handler.c pit_handler.h i8259.h types.h lib.h \
  scheduler.h
RTC.o: RTC.c RTC.h types.h i8259.h lib.h term_keyboard.h keyboard.h
scheduler.o: scheduler.c
sys_call_handler.o: sys_call_handler.c sys_call_handler.h types.h \
  term_keyboard.h keyboard.h lib.h RTC.h new_file.h x86_desc.h paging.h \
  scheduler.h
term_keyboard.o: term_keyboard.c term_keyboard.h keyboard.h types.h lib.h \
  sys_call_handler.h RTC.h new_file.h paging.h
tests.o: tests.c tests.h x86_desc.h types.h term_keyboard.h keyboard.h \
  lib.h RTC.h new_file.h
